version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rod
      MONGO_INITDB_ROOT_PASSWORD: rod

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rod
      ME_CONFIG_MONGODB_ADMINPASSWORD: rod
      ME_CONFIG_MONGODB_URL: mongodb://rod:rod@mongo:27017/
